---
services:
  main:
    image: docker.io/dmotte/svcbox-rootless:latest
    build: build
    restart: always
    hostname: svcbox-rootless
    ports: ["2222:2222"]
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ssh-host-keys:/ssh-host-keys
      - ./ssh-client-keys:/ssh-client-keys

volumes:
  ssh-host-keys: {}
